### ISSUE TITLE
script.reviewURL on rebuild_userChrome.uc.js

### ISSUE THREAD

**Issue by Mitezuss** [xiaoxiaoflood/firefox-scripts#102]
Maybe should be added reviewURL to userChrome.jsm for consistency

Regards

Extra: Maybe be nice have two new headers:

```
@compatibility (like alice0775 said) for check version of firefox and enable or disable (not show on the menu) the script
@changelog (alice0775 use the @version tag) a array with all changes, so can write multiples @changelog tags, like:
@changelog 1.0 bla bla
@changelog  1.1 fixed bla bla
and can be showed on the popup of rebuild_UCJS
```

**Comment by xiaoxiaoflood** [comment]
My userChromeJS doesn't support autoupdate scripts. Actually, I don't know any userChromeJS that supports autoupdating. If the user needs to manually update, they should already know what changed, what's the current version (my scripts also don't use version number), what's the page discussing the script (if any) and so on. Furthermore, users can always right-click the script in rebuild menu to open the code in editor, so that they can read the entire metablock.

Regarding compatibility, this is also very unclear, you never know if next version will be compatible with current script and it's not feasible to constantly update scripts just to mark compatibility version. Ultimately, user must test to see if it works. My scripts always target current DevEd.

So sorry, I currently don't plan to implement any of those.
