### ISSUE TITLE
For Linux Systems - There is a Discrepancy Between the "pref" Folder Provided by the Download Link and the "preferences" Folder that is actually Required

### ISSUE THREAD

**Issue by npn225** [xiaoxiaoflood/firefox-scripts#123]
When I followed the instructions for Linux users provided [here](https://github.com/xiaoxiaoflood/firefox-scripts) and [here](https://github.com/xiaoxiaoflood/firefox-scripts/issues/8#issuecomment-467619800), nothing worked. 

You see, the "fx-folder" download link from [here](https://github.com/xiaoxiaoflood/firefox-scripts) provides the "defaults/pref/" directory. 

But the comment from [here](https://github.com/xiaoxiaoflood/firefox-scripts/issues/8#issuecomment-467619800) says that name is "defaults/preferences/" for the directory. 

I finally did get things working by noticing this difference, then renaming "defaults/pref/" to "defaults/preferences/" and finally, clearing the startup cache. 

Don't know if this hasn't already been submitted as an issue because it's just obvious to everyone else, but I found this discrepancy to be quite confusing. 

Anyway, thanks for the great work!

**Comment by xiaoxiaoflood** [comment]
The zip file is provided to ease installation. Because Windows is way more popular than other OS - and I would even say that Windows user are, on average, less "tech experts" -, I think it's reasonable to present the instructions that way.

I just updated the [comment](https://github.com/xiaoxiaoflood/firefox-scripts/issues/8#issuecomment-467619800) linked in instructions trying to be clearer. I think this is enough.

**Comment by xiaoxiaoflood** [comment]
Updated again to be even more alarming of the differences. Not exactly as you requested. Just renaming `prefs` to `preferences` is not enough, `defaults` folder must be placed into `browser`, not in firefox root.
