### ISSUE TITLE
Waterfox G4.1.3 (64-bit) "Configuration Error"

### ISSUE THREAD

**Issue by CortexReaver** [xiaoxiaoflood/firefox-scripts#149]
After installing userChromeJS and clearing startup cache, Waterfox throws me this error. Seems like previous versions also does, but at least extensions there works fine. Done everything by the instruction.

![23-06-2022 194421](https://user-images.githubusercontent.com/34350690/175352071-7bf8fd43-33dd-465d-9a77-3cfc42ad12f8.png)

**Comment by xiaoxiaoflood** [comment]
Next Fx ESR (v102) will be released [in less than a week](https://wiki.mozilla.org/Release_Management/Calendar) so maybe it's not worth a proper fix.

As for now there are multiple ways to fix this. One of them is to use an [older version of config.js](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/ad2061bdaa9a5f77967029741a16614699a99f3a/installation-folder/config.js).

Other is to remove all these lines:
https://github.com/xiaoxiaoflood/firefox-scripts/blob/7f4e96000baf44398e7308b0aed24781ec29ea82/installation-folder/config.js#L5-L9

Other is to replace `ChromeUtils` here
https://github.com/xiaoxiaoflood/firefox-scripts/blob/7f4e96000baf44398e7308b0aed24781ec29ea82/installation-folder/config.js#L6
by `Cu.getGlobalForObject(Cu).ChromeUtils` or even just `Cu`.

**Comment by jis5ey** [comment]
I have the same issue in Waterfox 4.1.3.1 but also, I've noticed that I don't have anymore the button in the toolbar which I used to enable/disable custom scripts.

**Comment by xiaoxiaoflood** [comment]
Yes, thanks, but my reasoning is as follows: Waterfox don't need these files to install legacy extensions, they are natively supported. These file are required by Firefox users who want to run legacy extensions OR anyone wanting to run userChromeJS scripts.

That's OK, except that this is just a personal project I share for anyone who finds it useful. I use Fx Developer Edition, so DevEd is the only compatibility target. Or almost, because I also want userChromeJS, rebuild_userChrome and StyloaiX to be compatible with Thunderbird, which is based on ESR, so these are the only exceptions.

If I add something explicitly targeting Waterfox, users will expect that things here should be compatible with Waterfox and that's not the case, to simplify maintenance I always stated that I don't retain compatibility with versions older than DevEd.

So I might add this code, but doing that would probably cause misunderstanding i.e. wrong bug reports.

**Comment by xiaoxiaoflood** [comment]
Or better. Since signing bypass is only required for loading legacy extensions, I can simply move the code away from `config.js` and put it in  `BootstrapLoader.jsm`.

**Comment by onemen** [comment]
> Or better. Since signing bypass is only required for loading legacy extensions, I can simply move the code away from `config.js` and put it in `BootstrapLoader.jsm`.

It does not work in Firefox 102.

Every Firefox code that imports `AppConstants.jsm` before `BootstrapLoader.jsm` runs will have **MOZ_REQUIRE_SIGNING** set to true.

**Comment by onemen** [comment]
@xiaoxiaoflood, did you read the previous post ?

**Comment by xiaoxiaoflood** [comment]
@onemen

It always worked for me. It's working in Fx 104 DevEd and also in 102 release. BootstrapLoader.jsm runs very early. It would only be a issue for bootstrapLoader.xpi, but if you're able to install bootstrapLoader.xpi is because signing requirement is already disabled (DevEd, Nightly or unbranded) so doesn't matter.

**Comment by xiaoxiaoflood** [comment]
Closing this as it refers to old version.
