### ISSUE TITLE
Mouse Gestures script prevents Mouse Gestures extensions from working

### ISSUE THREAD

**Issue by zakius** [xiaoxiaoflood/firefox-scripts#150]
I use your script to ensure some gestures are available in all tabs, but due to the code complexity I supplement some actions with extensions. After recent updates of Quantum Dev I had to update your scripts and now I can't do that anymore. As soon as I disable your gestures script extensions start working again. I'm on 102.0b9 and tried both Foxy Gestures and Gesturefy, both simply never perform the bound action. Is there any chance you'd look at it?

**Comment by zakius** [comment]
update: it seems gestures are working, but rockers can't, I managed to set up everything like I needed to, but you may want to take a look at it

**Comment by xiaoxiaoflood** [comment]
> After recent updates of Quantum Dev I had to update your scripts and now I can't do that anymore.

Have you tested if an older version of mouseGestures.uc.js works for you?

**Comment by xiaoxiaoflood** [comment]
If you comment out or remove some `preventDefault` and `stopPropagation` it should fix, but I don't intend to change that because I want to prevent default click actions when a valid gesture is performed.

For instance, I use right-click + left-click to switch to last selected tab, but if I remove preventDefault it would allow the click in the page before switching the tab, which would follow a link if mouse was over one.

So MGest isn't really suited to be used along other gestures extension, it's normal they conflict.
