### ISSUE TITLE
Project dead??

### ISSUE THREAD

**Issue by marty60** [xiaoxiaoflood/firefox-scripts#20]
Does anyone know if this project is still active? I am able to still use script buttons with the change made in v69 to userChrome.jsm. Thanks to flandy for that. But I do miss some legacy addons like private tab and downthemall in the latest nightly. Given the code changes is it even possible to keep them working any longer?

**Comment by rubo77** [comment]
why should it be dead?

latest  committed on 30 Jul

**Comment by marty60** [comment]
There haven't been any addon updates since v68. I'm just speculating that maybe this is due to code changes in Firefox that make it impossible? Hope not since I'd love to see Private tab working again and a few others.

**Comment by xiaoxiaoflood** [comment]
Sometimes I take a break for 2 or 3 months... or more.

I just upgraded to Fx 69. Without dealing yet with some work in progress in Fx code like Megabar/Quantumbar and new about:addons (`extensions.htmlaboutaddons.enabled = false` almost required for the best use of Greasemonkey and Stylish).

I know that Fx 72 removed XBL, so maybe Fx 71 will be the end for almost all legacy addons. Unless someone helps, because it's still possible to convert to Custom Elements or something else. It's just too much work for me.

**Comment by marty60** [comment]
Thanks for your work xiaoxiaoflood and for the recent updates. I am once again thoroughly enjoying one of my favorite legacy addons Private Tab with today's nightly and it's working great. Don't know how long it will last given the constant changes but it sure beats opening up private windows. Addons like these should have been built into the browser.
