### ISSUE TITLE
BackTrack doesn't work on esr 102 portable and opens example.com

### ISSUE THREAD

**Issue by washwashx** [xiaoxiaoflood/firefox-scripts#204]
Hallo,
i've installed everything manually, quite easy, installed backtrack.xpi correctly.
when i restart firefox, and every time i open firefox, it opens a tab with example.com and a new window with the same url.
tried rebooting firefox, uninstall, reinstall, clear startup cache and so on in various order etc.
and the extension doesn't seem to work, something i did wrong?
esr 102 from portableapps.
application folder is FirefoxPortableESR102\App\Firefox64 if it matters.
i've used the "I'm only interested in extensions" zip
any clue? i'ts my fault?
i use win10 and ankerfox with little bit less options, but i removed the user.js file before installing everything...
i saw that inside the xpi various files there is "example.com" but i know nothing about how extensions works.
thank you.

**Comment by AlexVallat** [comment]
As Firefox is an ever-shifting target, I cannot commit to having BackTrack remain compatible with older versions of Firefox. It targets the latest developer and stable editions.

BackTrack will open a tab and a window with example.com in order to detect the timing for opening these windows, so it knows how long it takes to open a new tab or window on your system. You can avoid this by adding Number values to about:config of `extensions.backtrack.parentClickTimeoutTab` and `extensions.backtrack.parentClickTimeoutWindow`. These values are the number of ms it takes to open a new tab or window, so if you put 2000 for each it's probably safe enough. If you have a very slow computer and you think it takes longer than 2s to open a window, increase as appropriate.

However, if BackTrack isn't working well enough to do the window opening timing, then chances are it won't be working well for anything else either.

You could try downloading an older version from around the time 102 was current, it might work:
[v0.35.1](https://github.com/xiaoxiaoflood/firefox-scripts/blob/d779aeca032ba816d89a56db11171db1b0fbe4c7/extensions/backtrack/BackTrack.xpi)
[v0.34](https://github.com/xiaoxiaoflood/firefox-scripts/blob/b901b82e010e87dd0c993cc19435248e490fe975/extensions/backtrack/BackTrack.xpi)

**Comment by washwashx** [comment]
Thank you! v0.35.1 works with current esr 102 version!
but it's normal that it opens a tab and windows at every startup? i don't remember this behaviour many years ago...
anyway with 2000 setting works just fine and no tab and window.
how did you find it? how can i find older addons files version? 
for example...ESR user should use an older script? where can i find older fx-folder and utils* zips? 
102 ESR is currently supported for another year...is not really "old" , maybe other esr users would like to try it.
would be nice to have a link somewhere for the ESR, even with a disclaimer "if it doesn't works fine, no support, sorry".

PS. this page is impossible to find with google, looking for, for example..."legacy extension support for new firefox versions" and so on...
i found it randomly trying waterfox, that has lepton theme, then i tried to find a lepton theme for regular ff, then an update pointing that new lepton version now supports tabmixplus, and from there they say to use this script to use it.
Really strange, i'm going to post this github link in some forum because i saw there are many people (like me) that want the backtrack function and every answers i read was "no api for that so it's impossible"

**Comment by AlexVallat** [comment]
It is not normal to open a tab and window at every startup, it should only do that once, then the parentClickTimeout settings will be set and it will no longer try and recalculate them.

Git keeps full histories of all files, so you can get older versions of anything. You can go to [history](https://github.com/xiaoxiaoflood/firefox-scripts/commits/master), and go back through the dates, then click the < > button at any date to browse the whole repo as it was at that point in time.

I would generally recommend first trying the current version. If it doesn't work, then try an older version.

Yeah, we don't really do SEO or anything, but feel free to drop a link wherever you think people would be interested!
