### ISSUE TITLE
Breaks on Firefox 108

### ISSUE THREAD

**Issue by ElDani82** [xiaoxiaoflood/firefox-scripts#212]
I've been using this with LibreWolf for a while now, which is a more privacy-focused fork of Mozilla Firefox that is otherwise identical to the original. It worked on the last version 107.0.1-1 just fine, but the browser fails to start with the 108 update, whenever the contents of the fx-folder.zip are applied to the browser's installation directory.

Is there a way I could diagnose the root cause somehow? I only noticed the empty .startup-incomplete file in the profile folder, but couldn't locate any log files of the browser('s startup process).

**Comment by benyaminl** [comment]
This also break on Firefox 108, I mean they are the same, when you run on Linux, the error printed on terminal is, the script can't load `Missing chrome or resource URL: chrome://userchromejs/content/userChrome.jsm` , I think that's based on the config.js

**Comment by dv8472** [comment]
This sounds similar to my problem too.
OS: Arch Linux (not sure what all OSs are affected)
After I updated yesterday to FF v108, [I had problem with the TMP extension](https://github.com/onemen/TabMixPlus/issues/195).
Have updated the fx-folder.zip, and the FF did not start.
So far I've managed to find, that the [new content in config.js](https://github.com/xiaoxiaoflood/firefox-scripts/commit/66e896ec1514499557b64ce205104b04cdb8444a) just under the `// signing bypass by Dumby from forum.mozilla-russia.org` is the cause.
When I remove that particular part out of the config.js, I'm able to start FF, but I'm unable to install the add-on because of "_This add-on could not be installed because it has not been verified."_.
However, workaround (works until next FF restart, then I have to repeat this again) is possible through the "Debug Add-ons".

**Comment by savoury1** [comment]
Running latest Firefox 108 from deb package (not Snap) on Ubuntu and receiving the same error as @benyaminl mentioned in https://github.com/xiaoxiaoflood/firefox-scripts/issues/212#issuecomment-1355943179 above, specifically:
```
Missing chrome or resource URL: chrome://userchromejs/content/userChrome.jsm
```
Removing /usr/lib/firefox/config.js completely allows Firefox to load, didn't try removing just the code for signing bypass as @dv8472 mentioned in https://github.com/xiaoxiaoflood/firefox-scripts/issues/212#issuecomment-1356083075, but then there is no userChromeJS facility of course. So this is an additional confirmation that there is a notable issue with the latest Firefox 108 and the config.js script.

**Comment by benyaminl** [comment]
For another FYI, some other extension also broken on 108, I don't know why, some folks on /r/firefox said that noscript is broken, at least it's confirmed.

**Comment by alemenke** [comment]
I'm running version 108.0.1+build1-0ubuntu0.20.04.1  from the ubuntu repository. Firefox does not start with the config.js from https://github.com/xiaoxiaoflood/firefox-scripts/commit/66e896ec1514499557b64ce205104b04cdb8444a

Commenting out the added lines makes firefox start without a problem but unsigned addons like TMP don't work.

**Comment by eilegz** [comment]
i had a menu on tabs issues with Tab mix plus too, it was causing some elements to dissapear. had to disabled it to make it work again

**Comment by bemyak** [comment]
I stumbled upon this issue a couple of days ago and submitted a bug to their bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1805713

**Comment by xiaoxiaoflood** [comment]
Please try the updated `fx-folder.zip` (`config.js`).

**Comment by dv8472** [comment]
> Please try the updated `fx-folder.zip` (`config.js`).

The https://github.com/xiaoxiaoflood/firefox-scripts/commit/51a1b6c47a6e45dc411ba29dd1c017c7b0bf3f26 seems to work fine.
Browser starts, and allows installation of un-signed add-on.
Many thanks!

**Comment by bemyak** [comment]
I also confirm that the fix works! Thanks!

**Comment by savoury1** [comment]
Also working here. Thanks for the fix.
