### ISSUE TITLE
status-bar.uc.js new version for 109 makes browser-bottombar visible in fullscreen mode

### ISSUE THREAD

**Issue by rebmcr** [xiaoxiaoflood/firefox-scripts#236]
This is most apparent when using a video site such as YouTube. A 1080p video ends up slightly shrunk, rather than mapping 1:1 to the pixels on a 1080p display.

I'm seeing this behaviour on Windows 10.

**Comment by Lalarian** [comment]
Yep. I have the same issue here:
![statusbar](https://user-images.githubusercontent.com/5146616/214033703-51563aaf-70e5-4a37-86f4-ed99226c1631.png)
Also: The status bar in normal mode (non fullscreen) is higher than usual. If I disable the status bar in Firefox' 'View' menu, then the status bar gtes smaller and only the pure grey area that's also visible in fullscreen remains, but it's not working as a status bar- for exmple hovered links are not shown in the grey bar, but are floating at the loeft above the bar, in their default grey bubble.

**Comment by rebmcr** [comment]
It gets overwritten after a while, use this instead:
```
#browser-bottombox {
	display: contents!important;
}
```

**Comment by Lalarian** [comment]
Hi!
I tried both way, but for some reason none made a difference :(

`  GNU nano 7.2                                                                                            /usr/share/doc/matcha-gtk-theme/firefox/chrome/userChrome.css                                                                                                       

/* Import theme */

@import "Matcha/theme.css"; /**/

/*
 * Here you can enable other theme features not included by default.
 * To enable a specific feature, uncomment its @import line by removing "/*" at
 * the beginning of the line. To disable it, put the "/*" back.
 */

/* Hide the tab bar when only one tab is open (GNOMISH)
 * You should move the new tab button somewhere else for this to work, because by
 * default it is on the tab bar too. */
/*@import "Qogir/hide-single-tab.css"; /**/

/* Limit the URL bar's autocompletion popup's width to the URL bar's width (GNOMISH)
 * This feature is included by default for Firefox 70+. */
/*@import "Qogir/matching-autocomplete-width.css"; /**/

/* Use normal width tabs */
/*@import "Qogir/normal-width-tabs.css"; /**/

/* Active tab high contrast */
/*@import "Qogir/active-tab-contrast.css"; /**/

/* Use system theme icons instead of Adwaita icons included by theme */
/*@import "Qogir/system-icons.css"; /**/

/* Allow drag window from headerbar buttons (GNOMISH) [BUGGED]
 * It can activate button action, with unpleasant behavior. */
/*@import "Qogir/drag-window-headerbar-buttons.css"; /**/

/* Make all tab icons look kinda like symbolic icons */
/*@import "Qogir/symbolic-tab-icons.css"; /**/

/* Import a custom stylesheet
 * Everything you add in your customChrome.css file (it doesn't exist by
 * default) will be included here and preserved between updates, so you can move
 * your configuration to that file if you don't like setting it up after every
 * update. You can also apply your own custom styles in that file. */
@import "customChrome.css"; /**/

#browser-bottombox {
        display: contents!important;
}
`

**Comment by xiaoxiaoflood** [comment]
Thanks for reporting. Fixed in the new version I just uploaded.
