### ISSUE TITLE
Corrupt addon?

### ISSUE THREAD

**Issue by ElhemEnohpi** [xiaoxiaoflood/firefox-scripts#24]
I tried to install keyconfig.xpi, but I get a message that it's corrupt.

2. Change two about:config options as described, extensions.legacy.enabled true and xpinstall.signatures.required false
1. Install bootstrapLoader.xpi into Nightly 72.0.2 by downloading and dragging the file onto a browser window
3. Restart the browser
4. Download and try to install keyconfig.xpi or other .xpi file from this repository by dragging onto a browser window

Result: "This addon could not be installed, because it appears to be corrupt."

**Comment by xiaoxiaoflood** [comment]
> Nightly 72.0.2

This version doesn't exist.

keyconfig 2018.2.71.2020.01.21-xiao installs normally on Nightly 72.0a1 with bootstrap loader 0.1.70.2020.01.22.

And I don't guarantee that extensions will work on Fx 72+. Current compatibility can be seen in extension version, like keyconfig 2018.2.>>**71**<<.2020.01.21-xiao. Most extensions are still in Fx 70, since Fx 71 doesn't allow XBL and I don't even know if I can fix this, mainly DownThemAll! and QuickFox Notes that depend heavily on XBL.

**Comment by r-a-y** [comment]
> Nightly 72.0.2

This version does exist:
https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-release.revision.25e0edbb0a613c3bf794c93ba3aa0985d29d5ef4.firefox/win32-add-on-devel

Click on "target.zip"

**Comment by xiaoxiaoflood** [comment]
Right. I know unbranded release, I just think it sounds weird to call it Nightly. Unbranded has "Nightly" everywhere, but it's just release with `xpinstall.signatures.required` and `extensions.legacy.enabled` unlocked, it's not the Nightly we're used to (mozilla-central, inbound, autoland).

**Comment by xiaoxiaoflood** [comment]
Closing because keyconfig is working fine at least up to Fx 77, the version I'm using.
