### ISSUE TITLE
Delay in Asking for Password

### ISSUE THREAD

**Issue by skyworlka** [xiaoxiaoflood/firefox-scripts#29]
Hi,

Thanks for sharing your work.

I am asked for a password minutes after the browser opens & am already browsing. Also the input field can just be closed.

Firefox 74 64-bit
Windows 7 Ultimate

https://i.imgur.com/JgfVxGo.png
![Screenshot 20_03_28 11-36-39](https://user-images.githubusercontent.com/1270329/77810882-f7c89f80-70ea-11ea-810e-2ec0fe3beb2f.png)

Thanks again.

**Comment by xiaoxiaoflood** [comment]
Hi.

This is not caused by masterPasswordPlus.uc.js. Maybe something related to Firefox Sync (which I don't use), in this case it seems that you can change the timeout with `signon.masterPasswordReprompt.timeout_ms`.

There are [other causes](https://support.mozilla.org/en-US/kb/firefox-keeps-asking-me-master-password) that can make Firefox asks for master password, but it definitely has nothing to do with my script. Except that you need to define a master password to be able to use it, of course.
