### ISSUE TITLE
Greasemonkey dead + Future of addons in FF65?

### ISSUE THREAD

**Issue by dezhavu** [xiaoxiaoflood/firefox-scripts#3]
Hi there again

As of today's release (ff64) greasemonkey died :((

1544536957329	addons.manager	ERROR	Exception calling provider <unnamed-provider>.getAddonByID: ReferenceError: service is not defined(chrome://greasemonkey-modules/content/util/getService.js:6:3) JS Stack trace: getService@getService.js:6:3
ScriptAddonFactoryById@addons4.js:79:17
AddonProvider_getAddonByID@addons4.js:41:12
promiseCallProvider@AddonManager.jsm:226:12
async*getAddonByID/promises<@AddonManager.jsm:2163:12
getAddonByID@AddonManager.jsm:2162:20
getAddonByID@AddonManager.jsm:3280:12
@service.js:114:17
async*@service.js:113:2
@getService.js:3:1
GM_BrowserUI.chromeLoad@browser.js:59:3
_fireEventListener@Overlays.jsm:219:7
load@Overlays.jsm:182:9
load@Overlays.jsm:41:5
observe@bootstrap.js:257:11

1544536957331	addons.manager	ERROR	Exception calling provider <unnamed-provider>.getAddonByID: ReferenceError: service is not defined(chrome://greasemonkey-modules/content/util/getService.js:6:3) JS Stack trace: getService@getService.js:6:3
ScriptAddonFactoryById@addons4.js:79:17
AddonProvider_getAddonByID@addons4.js:41:12
promiseCallProvider@AddonManager.jsm:226:12
async*getAddonByID/promises<@AddonManager.jsm:2163:12
getAddonByID@AddonManager.jsm:2162:20
getAddonByID@AddonManager.jsm:3280:12
Config.prototype._updateVersion/<@config.js:310:19
async*Config.prototype._updateVersion@config.js:309:4
Config.prototype.initialize@config.js:29:3
@service.js:30:5
service.scriptUpdateData@service.js:36:7
service.broadcastScriptUpdates@service.js:48:14
@service.js:120:1
@getService.js:3:1
GM_BrowserUI.chromeLoad@browser.js:59:3
_fireEventListener@Overlays.jsm:219:7
load@Overlays.jsm:182:9
load@Overlays.jsm:41:5
observe@bootstrap.js:257:11

Can you get it back to life? It's usage on CSP enabled sites is crucial for me :(

Another question is that in Nightly ff65 all listed here addons are non functional..
I guess bootstrapped extensions as they were are dead, will need to convert to webextension experiments.

In case you will take a look at it, check out CB converted to webextension experiment, maintained by Infocatcher:
https://anonfile.com/Y5v7qandb4/custom_buttons-0.0.7.0.0.1-fx_xpi

**Comment by xiaoxiaoflood** [comment]
Updated. Read the how-to for Fx 65+.

Sometimes I get a month or two without touching Firefox scripts.

Thank you for the link. I'd rather keep extensions as legacy ones. WebEx Experiments work, but take a while to load, which in some edge cases it's a issue and need more fixes. With the solution I adopted, written by Mozilla devs, there is no need to change anything in addons.

I even packed my solution (BootstrapLoader.jsm) in a WebEx Experiment, so that one extension fix all the others. It works, but also may have some issues because of Experiments limitations.

So I chose the solution that is a little *harder* to the user to setup, but apparently returns exactly the way it was before Fx 65, without side effects.
