### ISSUE TITLE
Waterfox Current support?

### ISSUE THREAD

**Issue by maxoku** [xiaoxiaoflood/firefox-scripts#34]
Could you give some support to Waterfox Current that natively supports this format of legacy add-ons? It's based on Fx 68 though, so there might be so incomability with Fx 75.

I already use Stylish and DownThemAll from you. Though the newest version of DTA for Fx75 doesn't work here I use version 3.1.2.68.2019.07.01-xiao. Though it doesn't have a progressbar for downloaded files. I don't if that suppose to be or there is a more compatible version that would display progressbar while downloading?

Besides that would be possible for you to rewrite some other important add-ons? The one most important for me is TabMixPlus, but also FlashGot and  Custom Buttons. I've already requested developers of those add-ons to rewrite them, but in case they wouldn't agree, could you do it? Please consider my request.

**Comment by xiaoxiaoflood** [comment]
Hi,

I use Firefox Developer Edition, so it's the compatibility target. Things may or may not work on Waterfox, I don't know, I don't use it. Since Waterfox is based on Firefox ESR 68, you just need to see the history of `update.rdf` file of the desired extension.
Example:
https://github.com/xiaoxiaoflood/firefox-scripts/commits/master/extensions/DownThemAll/update.rdf
So here is the version supposed to work on Fx 68: https://github.com/xiaoxiaoflood/firefox-scripts/commit/2266572cbfc4f359f2c22ead6dd25c66025a3c3f

> Though it doesn't have a progressbar for downloaded files. I don't if that suppose to be or there is a more compatible version that would display progressbar while downloading?

No, I haven't remade progressbar since its removal in [bug 1430374](https://bugzilla.mozilla.org/show_bug.cgi?id=1430374). I'm fine with Percent column.

> Besides that would be possible for you to rewrite some other important add-ons?

No, sorry. This is a lot of work for extensions that I just don't use.
