### ISSUE TITLE
Cannot install DTA in Firefox Developer Edition 65.0b7 (64-bit), Win 8.1

### ISSUE THREAD

**Issue by noto10** [xiaoxiaoflood/firefox-scripts#4]
I have set the about:config entries but when I try to install DTA from file as per instructions, I get the following:

![2018-12-30_110904](https://user-images.githubusercontent.com/13828004/50544086-663b5b00-0c25-11e9-9f80-fa575d3b6296.jpg)

**Comment by xiaoxiaoflood** [comment]
This happens if you have not installed userChromeJS (or if you have not restarted Firefox after that).

Instead of userChromeJS, you can also try [bootstrapLoader](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions/bootstrapLoader).

Screenshot of DTA! in DevEd 65.0b7 64-bit Win 10, with userChromeJS:

![](https://i.imgur.com/B0s1xXa.png)
