### ISSUE TITLE
check on firefox 80, not work

### ISSUE THREAD

**Issue by hien4990** [xiaoxiaoflood/firefox-scripts#41]
im using firefox ver 80.1 and do as you write, nothing happen, there are not startupCache  file for me to delete.

**Comment by xiaoxiaoflood** [comment]
I use Developer Edition, currently v.79, so I can't guarantee it works on v,80.

`startupCache` is a folder, not a file. If you can't find it on your profile folder, maybe it's on `C:\Users\[user]\AppData\Local\Mozilla\Firefox\Profiles\[profile]`.

But since Fx 79 there's an easier way to clear startup cache. Open `about:support` and click `Clear startup cahce...`

**Comment by xiaoxiaoflood** [comment]
Tested and it's working.
