### ISSUE TITLE
UserScript manager and userscripts don't load on FF 64 stable(.02 x64 on windows 10 x64)

### ISSUE THREAD

**Issue by peterwx** [xiaoxiaoflood/firefox-scripts#5]
Followed the instructions but no UserScript (uc.js) manager appears.

**Comment by xiaoxiaoflood** [comment]
My userChromeJS uses [AutoConfig](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Enterprise_deployment_before_60#Configuration), which was [blocked](https://bugzilla.mozilla.org/show_bug.cgi?id=1455601) in stable and Beta since Fx 62.

You should use Developer Edition or Nightly, And I should add a note about this.
