### ISSUE TITLE
Could rebuild_userChrome.uc.js have a menu entry in the main (hamburger) menu rather than tools menu?

### ISSUE THREAD

**Issue by AlexVallat** [xiaoxiaoflood/firefox-scripts#51]
The tools menu is pretty hidden away on current versions of Firefox, only accessible through a shortcut key, so I was thinking a middle-ground between too visible (a toolbar button) and too hidden would be to have the menu on the main menu, perhaps below the Add-ons entry? Or is modifying this menu too much of a pain?

**Comment by xiaoxiaoflood** [comment]
Probably it's possible, but I never looked at how this hamburger menu works as I don't like it. I only know it's different from other XUL-based menus, so for example my "Keep Menu Open on Middle-Click" script doesn't work on it. I even hide this hamburger menu with CSS (StyloaiX), I don't find it useful for me.

So yes, it's possible, but I don't have plan to implement it, because this repo is mostly for sharing code I write for personal use - it may be useful for other people.

**Comment by AlexVallat** [comment]
Fair enough. Would you be interested in a PR for this? I've implemented it in a separate script, and modified ALWAYSEXECUTE to be an array so that multiple manager scripts can be defined, but if you would prefer to have a single ALWAYSEXECUTE script then this code could instead be merged into rebuild_userChrome.uc.js. My idea was that rather than having a pref for this, it would just be an optional script - if you don't have the script, you don't get the hamburger menu entry.

Code in here if interested: https://github.com/AlexVallat/firefox-scripts/blob/HamburgerMenuScriptList/chrome/userScriptsPanelMenu.uc.js

**Comment by xiaoxiaoflood** [comment]
Added. Thank you.
