### ISSUE TITLE
minMaxCloseButton

### ISSUE THREAD

**Issue by Orriky** [xiaoxiaoflood/firefox-scripts#76]
Hi,

Is it possible to use your script to start Firefox in a fixed position and with determined dimensions?

**Comment by xiaoxiaoflood** [comment]
Hi,

Fx remembers position and size from when it was closed the last time. You can probably use `resizeTo` and `moveTo` to achieve what you want. I won't add this to `minMaxCloseButton` because it's out of scope.

Example:
`resizeTo(600, 300)` to set window size to 600px width and 300px height.
`moveTo(200, 100)` to position the window as x: 200 and y: 100 (x: 0 and y: 0 is top-left).
