### ISSUE TITLE
MasterPassword not working in Waterfox Current

### ISSUE THREAD

**Issue by Avrution** [xiaoxiaoflood/firefox-scripts#82]
Not sure if this is made to work in this version, but the other scripts you have made work fine.  

This is pretty much the only thing I'm missing from getting my browser going the way I need it.

Unsure if it works at all in current browsers or if maybe things need to be tweaked?

**Comment by xiaoxiaoflood** [comment]
Things in this repo are made or maintained by me* for personal use. As I use Fx Developer Edition, I only test them on it. Things might or not work on other versions. I don't test on Nightly and I don't try to keep backward compatibility because this increase maintenance cost.

For extensions, `update.rdf` file should tell about backward compatibility. For instance, I guess that current DownThemAll! is compatible from v83 to current v89, but not that I made effort to do so.
https://github.com/xiaoxiaoflood/firefox-scripts/blob/e82e9fb20300605a0d43213bf9654a752746a802/extensions/DownThemAll/update.rdf#L8

But for scripts there's nothings saying about backward compatibility, they must work with the version listed in main page (currently that's Fx 89) and that's it.

MasterPassword+, StyloaiX and rebuild_userChrome.uc.js are exceptions because I try to keep them compatible with Thunderbird. TB uses Firefox ESR as base just as Waterfox Current does (afaik), so I believe it should work if you have everything updated (not just the .uc.js, make sure that your utils folder is always updated). But I don't have Waterfox here to test.

And after updating your utils folder, make sure to clear startup-cache on restart.

*: exceptions: I'm not responsible for the last three script listed in readme and also the extension BackTrack Tab History. I use BackTrack, so I can state it works, but I never used the tree scripts.

**Comment by Avrution** [comment]
Everything is updated as I just did a new install.  It seems the option to clear the startup-cache is gone from the about:support so I just deleted the startupCache folder.

userchromejsmanager and extensions options menu both work fine.  

Removed master password and readded, but still no prompts nor ability to lock.

**Comment by xiaoxiaoflood** [comment]
>  It seems the option to clear the startup-cache is gone from the about:support

That button was added in Fx 80. I guess WC is based on Fx 78, that's why you don't see it.

---

Well, if you really want to use MP+ I suggest you to try an old version of it.

**Comment by Avrution** [comment]
Issue is resolved.  Somehow, when the file was first downloaded it ended up being hundreds and hundreds of lines long - only found that out when trying an older version.  

Latest version works perfectly in WF current.

Thanks again.
