### ISSUE TITLE
What is intended behavior for EnterSelects?

### ISSUE THREAD

**Issue by e-t-l** [xiaoxiaoflood/firefox-scripts#83]
I installed EnterSelects, followed all instructions exactly, but as far as I can tell there's no change in behavior. What exactly is it supposed to do or look like? Should it in-line autofill the first drop-down result?

**Comment by xiaoxiaoflood** [comment]
No, it doesn't autofill anything. It just pre-selects the first suggestion, so that if you press Enter Firefox will load it.

What Enter Selects does, basically, is to skip the needing to press down arrow key (↓) to select the first result.

Because Firefox autofill is domain-only, so often the page you want to load is not the one auto-filled BUT it's the first suggestion.

For instance... How do I open this repo? I just type "xi" and press Enter:
![image](https://user-images.githubusercontent.com/25161346/118429516-40a13600-b6a8-11eb-925e-2d622977e4fa.png)
