### ISSUE TITLE
Doesn't work with portable firefox?

### ISSUE THREAD

**Issue by mimteatr** [xiaoxiaoflood/firefox-scripts#93]
Hello,

In my desktop FF at home it works perfectly but at work, I'm using the FF portable version from PortableApps and it doesn't. But other CSS do work. What could I be doing wrong? 
I followed your steps carefully several times with no result :(

Thanks for your help!

Maurice

**Comment by xiaoxiaoflood** [comment]
Hi,

I don't use Fx portable so I don't know what's different about it, sorry. I guess you just need to be more careful about *installation* & profile paths, but other than that I doubt there's any incompatibility.

As stated in Readme, I only test things in Developer Edition because that's what I use (this is a personal project that I share if someone finds it useful). Things *may* work on other versions (release, Beta, ESR, forks like Waterfox...), but I don't fix anything with any of these versions in mind.

**Comment by mimteatr** [comment]
I understand. I'll try again. 
Btw, the enterSelects.uc.js disables the "and Go" from  the Paste and Go option on the urlbar drop-down menu. I discovered that by disabling each script one by one and restarting FF every time.

**Comment by xiaoxiaoflood** [comment]
Thanks for reporting, but could you please explain more? Where is this "and Go"? Maybe a screenshot...

**Comment by mimteatr** [comment]
Hi, left clicking on urlbar, see the **Paste and Go** on the image. What I meant is that with that script you don't see the **and Go** anymore, only **Paste**.

https://imgur.com/a/BvqB1to

**Comment by xiaoxiaoflood** [comment]
@mimteatr thanks. I would never notice this bug if it wasn't you. This should be fixed now, please update the script if you use it.

**Comment by mimteatr** [comment]
👌😊

**Comment by harryray33** [comment]
Same problem here, Im using ff portable 88.0.1 and it's not working, although it was kind of working back in FF69 but the add-ons page was disappearing.
